### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by chrisbrucewilliams** [IndyJoeA/cbpi_Tilt#1]
I'm running the CBP software and installed the Tilt Plugin.  I've also gone through your installation:
  -  sudo apt-get install python-bluez
  -  sudo setcap cap_net_raw+eip /usr/bin/python2.7 (One thing to note, on your Gitbub page it is NOT clear there is a space between eip and /usr, I missed this at first).  

I can configure a tile sensor in CBP but no data shows up.  In the ReadME you mention something about ibeacon_scanner but I did not install this.  Do I need to install this?  I did not pair the tilt device, do I need to pair it?  How do you get the tilts to be seen?

**Comment by IndyJoeA** [comment]
No, you shouldn't need to pair it, if you have selected the right color of the Tilt from the plugin config screen (red, blue, black, etc).  

Some questions: 
1)  Does your Tilt connect to the iPhone/Android app?  You can run the app at the same time as CBPi to see if it is communicating. 
2)  What model of Raspberry Pi do you have?  Some models do not have Bluetooth built in. 
3)  Check the log file located at /craftbeerpi3/logs/tilt.log.  This log will list any errors with starting the Bluetooth connection.

**Comment by IndyJoeA** [comment]
Closed, issue turned out to be with the device
