### ISSUE TITLE
Missing module numpy

### ISSUE THREAD

**Issue by spanznet** [IndyJoeA/cbpi_Tilt#3]
I've done 2 fresh installs recently and both times after all the raspbian updates, and craftbeerpi 3 git pull and tilt addon install, I get a message about missing module numpy.   Which is fixed with "sudo pip install numpy" - not sure if I'm missing something, or if it's worth adding to install instructions?

**Comment by IndyJoeA** [comment]
Thanks for the feedback, I have added the instructions to install numpy to the readme.  This library was included before but I guess it is not in the latest builds.
